component abspos "Increment absolute position";
pin in float in0;
pin in float in1; //Reset pin
pin out float out0;
pin out float out1;
pin out float out2; //Testpin for reseting old pos
param rw float old;
param rw float prev_update;
function _;
license "GPL"; // indicates GPL v2 or later
;;
if (prev_update != in1 && in1 != 0.0) 
{
    old = in1;
    prev_update = in1;
    out0 = in0 + old;
}
else
{
    out0 = in0 + old;
    old = in0;
}
out1 = old;
out2 = prev_update;
